From maven:3.8.6-openjdk-8

WORKDIR /usr/src/mymaven/target
ENV TZ=Asia/Shanghai
RUN ln -sf /usr/share/zoneinfo/$TZ /etc/localtime    && echo $TZ > /etc/timezone

COPY ./target/getSign-0.0.1.jar ./

ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=prod", "-Xms3g", "-Xmx3g", "-Xmn2g", "/usr/src/mymaven/getSign-0.0.1.jar"]
