server:
  port: 8083

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


system:
  whitelist:
    - /userQuery/getUserInfo
    - /menuQuery/userMenuTreeQuery
    - /systemQuery/querySystemInfoPage
    - /user/modifyPassword
    - /permissionQuery/getPermissionByUser